# -*- coding: utf-8 -*-
"""street-data-loading.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YKN_YG3pHMaC993eHiFZD3X8HyzOe0PD
"""

pip install -U requests pyquery

import pandas as pd
import requests
from pyquery import PyQuery as pq

url_csv_github = "https://raw.githubusercontent.com/rtbfinfo/brussels_street/main/brussels_streets_cleaned.csv"
file_csv_output = "brussels_street_complete.csv"

"""## Chargement du fichier CSV"""

df = pd.read_csv(url_csv_github, delimiter=";")
df.head()

"""## Récupération des descriptions en ligne"""

def get_description(url):
  r = requests.get(url)
  html = pq(r.text)
  data = ""
  for item in html("font").text():
    data = data + item
  return data

# get_description("https://www.ebru.be/Streets/bruxelles-1000-place-des-3-septembre.html")

descriptions = []
for row in df["Lien"]:
  descriptions.append(get_description(row))

df["Description"]=descriptions

"""## Save a new CSV"""

df.to_csv("brussels-streets-with-description.csv")